import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';
import Link from 'next/link'
import DatePicker from "react-datepicker"
import "react-datepicker/dist/react-datepicker.css"
import Cookie from "js-cookie"
import { useRouter } from 'next/router'
import AddNofi from '../components/nofication';
import { Input, Dropdown } from "@nextui-org/react";
import axios from 'axios';


export default function register() {
    let option_ids = [0, 1, 2]
    const [scrollY, setScrollY] = useState(0);
    const [option_id, setoption_id] = useState(option_ids)
    const [mailcolor,setMailcolor] = useState("success")
    const [error,setError] = useState('')
    const [nof,setnof] = useState(false)
    const [inputValues,setInputValues] =useState({})
    let env = 'http://localhost:5001/'
    const headers = {
        'Content-Type': 'application/x-www-form-urlencoded'
    };

    function handleChange(evt) {
        setnof(false)
        const value = evt.target.value;
        setInputValues({
    ...inputValues,
    [evt.target.name]: value
    })

    }

const registerbuttonclick = event => {


        event.preventDefault();

        if(inputValues['password'] == inputValues['rpassword'] ){
            axios.post(env+'register',inputValues,{headers})
            .then((res)=>{
                if(res.data == "have"){
                    setError('Алдаа - Бүртгэлтэй майл хаяг байна')
                    setnof(true)
                    
                } else if (res.data == "unsuccessfull"){
                    setError('Алдаа - Сервер')
                    setnof(true)
                    
                } else {
                    setError('Амжиллтай үүслээ')
                    setnof(true)
                    router.push({
                        pathname:'/login',
                    }
                      )

                }
            }).catch((err)=>{console.log(err)})

        } else {
            
            setError('Алдаа - Нууц үг таарахгүй  байна')
            setnof(true)
        }
    }
    const router = useRouter()

    let options = [
        { value: 'Хүйс сонгоно уу' },
        { value: 'Эрэгтэй' },
        { value: 'Эмэгтэй' }
    ]
    const stylesq ={
        1:{
            width: "250px", height: "80px", marginTop: "10px" ,color:"White"
        },
        2:{
            width: "90%", height: "80px", marginTop: "10px" ,color:"White"
        },

    }

    useEffect(() => {
        const handleResize = () => {
          setScrollY(window.innerWidth,);
        };
        window.addEventListener("resize", handleResize);
        return () => {
            window.removeEventListener("resize", handleResize)
        };
      }, []);


    return (


        <div className={styles.rlogincontainer}>

            <Head>
                <title>Бүртгүүлэх - BML</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className={styles.span1} >
                Бүртгүүлэх
            </div>
            <span className={styles.span2}>
                BML тавтай морилно уу
            </span>

        
            <form className={styles.rforms} onSubmit={registerbuttonclick}>
                <Input required value={inputValues['fname']}   onChange={handleChange} color="warning"   css={scrollY > 400 ? stylesq[1] :stylesq[2]}
                  
                    size="lg" className='inputsss'  type="text" name="fname" label='Овог' />
                <Input  required value={inputValues['lname']} onChange={handleChange} color="warning"   css={scrollY > 400 ? stylesq[1] :stylesq[2]} size="lg" type="text" name="lname" label='Нэр' />

                <Input required value={inputValues['mail']} name="mail" onChange={handleChange} color="warning"  css={scrollY > 400 ? stylesq[1] :stylesq[2]} size="lg" type="email" key="mail" label="Майл хаяг оруулах" ></Input>
                <Input  required value={inputValues['phonenumber']} name="phonenumber"   onChange={handleChange} color="warning"  css={scrollY > 400 ? stylesq[1] :stylesq[2]} size="lg" type="tel" key="phonenumber" label="Утасны дугаар оруулах" ></Input>
                <Input.Password  required value={inputValues['password']} name="password"  onChange={handleChange}   color="warning"   css={scrollY > 400 ? stylesq[1] :stylesq[2]} size="lg" key="password" label='Нууц үг' />
                <Input.Password required value={inputValues['rpassword']}  name="rpassword" onChange={handleChange} color="warning" css={scrollY > 400 ? stylesq[1] :stylesq[2]} size="lg" id="ret" key='retpassword' label='Нууц үг давтан оруулах' />
                <button  className={styles.buttons}  >

                Үргэлжлүүлэх
            </button>
                </form>
        
            
            

            <div className={styles.register}> <ul>Бүртгэлтэй хэрэглэгч,</ul> <Link href='/login' > Нэвтрэх  </Link></div>
            {nof&&<AddNofi error={error} />}
        </div>


    )
}
